apiVersion: v1
kind: Secret
metadata:
  name: library-api-secrets
  namespace: library
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-odd-silence-a40domjt-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "neondb_owner"
  SPRING_DATASOURCE_PASSWORD: "npg_Jtb9m3RZdeIG"
  JWT_SECRET: "aVerySecureJwtSecretKeyThatIsAtLeast32CharactersLongForTestingPurposes"
